### ISSUE TITLE
Is there any way to make this work on Ubuntu 20.04?

### ISSUE THREAD

**Issue by nickchomey** [strang1ato/nhi#17]

**Comment by strang1ato** [comment]
@nickchomey Ubuntu 20.04 comes with linux kernel 5.4, however kernel 5.5+ is required by nhi. If you upgrade your kernel to 5.5+ then nhi should work fine.

**Comment by nickchomey** [comment]
Thanks. I think I will pass on this for now as I'd imagine that it could create problems to use a kernel that is not officially supported by Ubuntu. When the major packages that I use announce that they support 22.04, I'll upgrade and try nhi then.

**Comment by strang1ato** [comment]
@nickchomey I will start working on adding support to ubuntu 22.04 in the second half of may (when I will be less busy)
