### ISSUE TITLE
libbpf: elf: legacy map definitions in 'maps' section are not supported by libbpf v1.0+

### ISSUE THREAD

**Issue by kamheric** [strang1ato/nhi#19]
eBPF 1.0 : Support for legacy BPF map definitions in SEC("maps") was completely [dropped](https://nakryiko.com/posts/libbpf-v1/).

so, i cant try nhi on my ArchLinux : 
` journalctl -u nhid.service`
> nhid[4612]: libbpf: elf: legacy map definitions in 'maps' section are not supported by libbpf v1.0+

**Comment by strang1ato** [comment]
Thank you for showing interest in this project and for reporting this urgent issue.
Fixed by https://github.com/strang1ato/nhi/commit/f800717f80296007d97438e62e5bbc58f1a800d7
