### ISSUE TITLE
WAL grows gigabytes

### ISSUE THREAD

**Issue by pexes123** [strang1ato/nhi#25]
Hi Karol, thanks for building this tool, I run it for a while and it saved me couple of times.

On my system, nhi sqlite WAL likes to grow quickly to gigabytes of size
```
:/var/nhi$ ll
total 1310705
drwxr-xr-x  2 root root           5 jún 10 13:47 ./
drwxr-xr-x 15 root root          17 jan 23  2024 ../
-rwxr-xr-x  1 root root    27152384 sep  2 12:32 db*
-rwxr-xr-x  1 root root       32768 sep  2 12:32 db-shm*
-rwxr-xr-x  1 root root 10299085392 sep  2 12:32 db-wal*
```

Usually I stop the service and do some sqlite to shrink/truncate it
```
PRAGMA journal_size_limit;
PRAGMA journal_size_limit=1000;
PRAGMA wal_checkpoint(RESTART);
PRAGMA wal_checkpoint(PASSIVE);
PRAGMA wal_checkpoint(TRUNCATE);
```

After less than a day of minimum shell interaction it is 100MB+
```
:/var/nhi$ ll
total 25113
drwxr-xr-x  2 root root         5 Sep  2 17:23 ./
drwxr-xr-x 15 root root        17 Jan 23  2024 ../
-rwxr-xr-x  1 root root  29954048 Sep  3 12:33 db*
-rwxr-xr-x  1 root root     32768 Sep  3 12:33 db-shm*
-rwxr-xr-x  1 root root 135889992 Sep  3 12:33 db-wal*
```

And as I was writing this message, it has grown over 500MB:
```
:/var/nhi$ ll                  
total 85709
drwxr-xr-x  2 root root         5 Sep  2 17:23 ./
drwxr-xr-x 15 root root        17 Jan 23  2024 ../
-rwxr-xr-x  1 root root  29954048 Sep  3 12:48 db*
-rwxr-xr-x  1 root root   1048576 Sep  3 12:48 db-shm*
-rwxr-xr-x  1 root root 532365832 Sep  3 12:48 db-wal*
```

Autocheckpoint is disabled from this commit https://github.com/strang1ato/nhi/commit/7b1d30a26aded93883caa2f96351b6149eb81d67 , and checkpoinitng is done with calls like this
```
  if (sqlite3_wal_checkpoint(db, 0) != SQLITE_OK) {
    write_log(sqlite3_errmsg(db));
  }
```
I can only confirm this calls apparently pass OK, as there are no sqlite errors in /tmp/nhi.log

What do you think can cause the WAL to grow

**Comment by strang1ato** [comment]
That's nice that you found this tool useful. You can check the db manually with sqlitebrowser and see what is taking up the space

**Comment by pexes123** [comment]
Not aware of any tool that reads db-wal and have not yet gone as far as view in hex editor

If you backport the latest version to jammy, I try if update helps
```
apt list -a nhi
Listing... Done
nhi/jammy,now 0.2.4~ubuntu22.04 amd64 [installed]
```
